"""Generate matching source fingerprints for the Worker bundle and Container image."""

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIRECTORIES = ("worker", "routes", "services", "providers", "streaming", "middleware", "static", "templates", "scripts")
SUFFIXES = {".py", ".mjs", ".js", ".css", ".html", ".sh"}


def fingerprint(root=ROOT):
    paths = set(root.glob("*.py"))
    paths.update(root / name for name in ("cloudflare-worker.mjs", "Dockerfile", "requirements.lock"))
    for directory in DIRECTORIES:
        paths.update(path for path in (root / directory).rglob("*") if path.is_file() and path.suffix in SUFFIXES)
    digest = hashlib.sha256()
    for path in sorted(paths):
        if path == root / "worker/build-id.mjs":
            continue
        digest.update(path.relative_to(root).as_posix().encode() + b"\0")
        digest.update(path.read_bytes() + b"\0")
    return digest.hexdigest()


def main():
    build_id = fingerprint()
    (ROOT / "worker/build-id.mjs").write_text(f'// Generated by scripts/build_release_metadata.py.\nexport const BUILD_ID = "{build_id}";\n')
    (ROOT / ".container-build-id").write_text(build_id + "\n")
    print("Release fingerprints generated.")


if __name__ == "__main__":
    main()
