import base64

# Base64 encoded minimal proxy icon (you can replace this with your own icon)
FAVICON_BASE64 = '''
AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIi
IgwiIiIMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIiDCIiIgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAiIiJkIiIiZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiImQiIiJkAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAIiIi/yIiIv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIiL/IiIi/wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAACIiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACIiIj///////////////////////////////////////////+IiIj/AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAACIiIj///////////////////////////////////////////+IiIj/AA
AAAAAAAAAAAAAAAAAAAAAAAAAAAACIiIj///////////////////////////////////////////+IiIj/
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/
iIiI/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIiL/IiIi/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CIiIv8iIiL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIiZCIiImQAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAiIiJkIiIiZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiIgwiIiIMAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAiIiIMIiIiDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP
//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AA
A==
'''

# Save the favicon
with open('static/favicon.ico', 'wb') as f:
    f.write(base64.b64decode(FAVICON_BASE64)) 