"""Local validation and compact rendering mirror the handoff Worker contract."""
import json
import re

SECTION_COUNTS = {"files": 100, "decisions": 30, "failed_attempts": 30,
                  "commands": 30, "next_steps": 30, "open_questions": 20}


def fields(value, allowed, required=()):
    if not isinstance(value, dict) or set(value) - set(allowed) or set(required) - set(value):
        raise ValueError("Missing or unsupported handoff fields")


def text(value, maximum, required=False):
    if (not isinstance(value, str) or len(value) > maximum or (required and not value.strip())
            or re.search(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", value)):
        raise ValueError("Invalid handoff string")
    return value


def sections(value):
    fields(value, ("goal", "state", *SECTION_COUNTS))
    result = {name: text(value.get(name, ""), 500) for name in ("goal", "state")}
    for name, maximum in SECTION_COUNTS.items():
        items = value.get(name, [])
        if not isinstance(items, list) or len(items) > maximum:
            raise ValueError("Invalid handoff section count")
        result[name] = []
        for item in items:
            if name in {"files", "commands"}:
                keys = ("path", "change") if name == "files" else ("command", "outcome")
                fields(item, keys, keys)
                result[name].append({key: text(item[key], 500) for key in keys})
            else:
                result[name].append(text(item, 500))
    return result


def validate_payload(value):
    fields(value, ("project", "branch", "title", "summary", "sections", "source", "ttl_days"),
           ("project", "title", "sections", "source"))
    fields(value["source"], ("agent", "thread_id"), ("agent",))
    source = value["source"]
    if source["agent"] not in {"claude", "codex", "opencode", "other"}:
        raise ValueError("Invalid handoff source")
    if "thread_id" in source:
        text(source["thread_id"], 200)
    ttl = value.get("ttl_days", 14)
    if type(ttl) is not int or not 1 <= ttl <= 90:
        raise ValueError("Invalid handoff TTL")
    result = {"project": text(value["project"], 200, True), "branch": text(value.get("branch", ""), 200),
              "title": text(value["title"], 200), "summary": text(value.get("summary", ""), 4000),
              "sections": sections(value["sections"]), "source": dict(source), "ttl_days": ttl}
    # Reserve room for the UUID and timestamps generated by the store.
    record = {key: item for key, item in result.items() if key != "ttl_days"}
    record.update(id="0" * 36, created_at="0" * 24, expires_at="0" * 24)
    if len(json.dumps(record, ensure_ascii=False, separators=(",", ":")).encode()) > 32768:
        raise ValueError("Handoff exceeds 32 KB")
    return result


def render(value):
    s = sections(value["sections"])
    metadata = value["project"] + (" ({})".format(value["branch"]) if value.get("branch") else "")
    metadata += " · " + value["source"]["agent"]
    if value.get("created_at"):
        metadata += " · " + value["created_at"]
    lines = ["# " + value["title"], metadata, "Goal: " + s["goal"], "State: " + s["state"]]
    for name, items in (("Next steps", s["next_steps"]), ("Open questions", s["open_questions"]),
                        ("Files", ["{path}: {change}".format(**item) for item in s["files"]]),
                        ("Decisions", s["decisions"]), ("Failed attempts", s["failed_attempts"]),
                        ("Commands", ["{command}: {outcome}".format(**item) for item in s["commands"]])):
        if items:
            lines.extend([f"\n{name}:", *(f"- {item}" for item in items)])
    if value.get("summary"):
        lines.append("\nSummary: " + value["summary"])
    encoded = "\n".join(lines).encode()
    return encoded.decode() if len(encoded) <= 4500 else encoded[:4496].decode("utf-8", "ignore") + "\n…"
