"""Serve the control plane with synthetic data for local interface review.

The preview never reads `.env` files, removes inherited credentials, keeps every
database in a temporary directory, and refuses non-loopback network connections.
No provider can be called or billed. Fixtures live in `preview_fixtures.py` and
are installed only by this script.

    .venv/bin/python scripts/preview_ui.py --port 5057

Sign in as `admin` with the key printed at startup.
"""

from __future__ import annotations

import argparse
import atexit
import errno
import ipaddress
import os
import re
import secrets
import shutil
import signal
import socket
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = Path(__file__).resolve().parent
CREDENTIAL_NAME = re.compile(r"KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL|DATABASE_URL", re.IGNORECASE)
PREVIEW_PROVIDER_CREDENTIALS = (
    "OPENROUTER_API_KEY",
    "NANOGPT_API_KEY",
    "NANOGPT_API_KEY_1",
    "GROQ_API_KEY_1",
    "OPENCODE_GO_API_KEY",
    "KIMI_CODE_API_KEY",
    "NAVYAI_API_KEY",
)


def _is_local_host(host) -> bool:
    if host in (None, "localhost"):
        return True
    try:
        return ipaddress.ip_address(str(host).split("%", 1)[0]).is_loopback
    except ValueError:
        return False


def guard_outbound_network() -> None:
    """Allow loopback and Unix sockets only, so provider calls fail immediately."""
    original_connect = socket.socket.connect
    original_connect_ex = socket.socket.connect_ex
    original_getaddrinfo = socket.getaddrinfo

    def permitted(sock, address) -> bool:
        if sock.family == getattr(socket, "AF_UNIX", object()):
            return True
        return isinstance(address, tuple) and _is_local_host(address[0])

    def connect(sock, address):
        if not permitted(sock, address):
            raise ConnectionRefusedError(errno.ECONNREFUSED, "Outbound network is disabled in the UI preview")
        return original_connect(sock, address)

    def connect_ex(sock, address):
        if not permitted(sock, address):
            return errno.ECONNREFUSED
        return original_connect_ex(sock, address)

    def getaddrinfo(host, *args, **kwargs):
        if not _is_local_host(host):
            raise socket.gaierror(socket.EAI_NONAME, "Name resolution is disabled in the UI preview")
        return original_getaddrinfo(host, *args, **kwargs)

    socket.socket.connect = connect
    socket.socket.connect_ex = connect_ex
    socket.getaddrinfo = getaddrinfo


def configure_environment(state_dir: Path, admin_key: str) -> None:
    for name in [name for name in os.environ if CREDENTIAL_NAME.search(name)]:
        del os.environ[name]
    for name in [name for name in os.environ if name.startswith(("KNOWLEDGE_", "WORKBENCH_", "CONTROL_PLANE_"))]:
        del os.environ[name]
    os.environ.update({
        "FLASK_ENV": "development",
        "FLASK_SECRET_KEY": secrets.token_urlsafe(32),
        "JWT_SECRET": secrets.token_urlsafe(32),
        "ADMIN_USERNAME": "admin",
        "ADMIN_API_KEY": admin_key,
        "AUTH_DB_PATH": str(state_dir / "auth.sqlite3"),
        "MODEL_REGISTRY_DB_PATH": str(state_dir / "model_registry.sqlite3"),
        "RATE_LIMIT_DB_PATH": str(state_dir / "rate_limits.sqlite3"),
        "CONNECTION_PROFILES_DB_PATH": str(state_dir / "workbench.sqlite3"),
        "LOG_LEVEL": "WARNING",
    })
    for name in PREVIEW_PROVIDER_CREDENTIALS:
        os.environ[name] = f"preview-{name.lower()}-not-a-real-credential"


def disable_env_files() -> None:
    """Keep the real `.env` unread by both the project loader and Flask's dotenv support."""
    # Flask's `app.run()` otherwise loads `.env` from the working directory.
    os.environ["FLASK_SKIP_DOTENV"] = "1"
    import env_loader

    env_loader.load_runtime_env = lambda *args, **kwargs: None


def assert_synthetic_credentials() -> None:
    """Refuse to serve if any credential outside the synthetic set reached the process."""
    allowed = {"FLASK_SECRET_KEY", "JWT_SECRET", "ADMIN_API_KEY", *PREVIEW_PROVIDER_CREDENTIALS}
    unexpected = sorted(name for name in os.environ if CREDENTIAL_NAME.search(name) and name not in allowed)
    if unexpected:
        raise RuntimeError(f"Refusing to serve: non-synthetic credential variables are present: {', '.join(unexpected)}")


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--host", default="127.0.0.1", help="Bind address (default: loopback only)")
    parser.add_argument("--port", type=int, default=5057)
    parser.add_argument("--admin-key", help="Synthetic admin key; a random key is generated by default")
    parser.add_argument("--knowledge", choices=("connected", "setup", "unavailable"), default="connected",
                        help="Knowledge service state to simulate")
    parser.add_argument("--no-badge", action="store_true", help="Hide the synthetic-data badge")
    return parser.parse_args(argv)


def main(argv=None) -> None:
    args = parse_args(argv)
    admin_key = args.admin_key or f"preview-admin-{secrets.token_urlsafe(12)}"
    state_dir = Path(tempfile.mkdtemp(prefix="multillm-ui-preview-"))
    atexit.register(shutil.rmtree, state_dir, True)
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    configure_environment(state_dir, admin_key)
    guard_outbound_network()
    sys.path[:0] = [str(ROOT), str(SCRIPTS)]
    os.chdir(ROOT)
    disable_env_files()

    import app as app_module
    import preview_fixtures

    application = app_module.app
    application.config["IMAGE_RELAY_CATALOG_AUTO_REFRESH"] = False
    # Reviewers edit templates while the preview runs; production keeps Jinja's cache.
    # The config key matters: app.run(debug=False) otherwise resets auto_reload.
    application.config["TEMPLATES_AUTO_RELOAD"] = True
    application.jinja_env.auto_reload = True
    preview_fixtures.install(application, knowledge_mode=args.knowledge, badge=not args.no_badge)
    assert_synthetic_credentials()
    application.before_request(assert_synthetic_credentials)

    print(f"MultiLLM UI preview: http://{args.host}:{args.port}/login", flush=True)
    print(f"Sign in as admin with key: {admin_key}", flush=True)
    print(f"Synthetic state directory (removed on exit): {state_dir}", flush=True)
    application.run(host=args.host, port=args.port, threaded=True, use_reloader=False, debug=False,
                    load_dotenv=False)


if __name__ == "__main__":
    main()
